version: '3.9'

networks:
  ipehr-network:
    driver: bridge

services: 
  ipehr-index:
    image: ghcr.io/bsn-si/ipehr-blockchain-indexes:develop
    ports:
      - 8545:8545
    networks:
      - ipehr-network
    healthcheck:
      test: 'curl --fail -X POST http://0.0.0.0:8545 -H "Content-Type: application/json" --data "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"eth_chainId\",\"params\":[]}" || exit 1'
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  ipehr-stat:
    build:
      context: .
      dockerfile: Dockerfile.stat
    image: ipehr-stat
    pull_policy: never
    depends_on:
      ipehr-index:
        condition: service_healthy
    ports:
      - 8081:8080
    configs:
      - source: stats-config
        target: /srv/config.json
    networks:
      - ipehr-network

  ipehr-gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    image: ipehr-gateway
    pull_policy: never
    environment:
      - GIN_MODE=release
    configs:
      - source: gateway-config
        target: /srv/config.json

    depends_on:
      ipehr-index:
        condition: service_healthy
      ipehr-stat:
        condition: service_started
    ports:
      - 8080:8080
    networks:
      - ipehr-network

configs:
  gateway-config:
    file: ./ci/gateway-config.json
  stats-config:
    file: ./ci/stats-config.json
