version: '3.9'

services: 
  ipehr-index:
    image: ghcr.io/bsn-si/ipehr-blockchain-indexes:develop
    ports:
      - 8545:8545
    networks:
      - ipehr-network
    command: npx hardhat node & npx hardhat run scripts/deploy.ts --network localhost & sleep infinity & wait
    healthcheck:
      test: 'curl --fail -X POST http://localhost:8545 -H "Content-Type: application/json" --data "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"eth_chainId\",\"params\":[]}" || exit 1'
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 10s

  ipehr-stat:
    image: ghcr.io/bsn-si/ipehr-stat:develop
    depends_on:
      ipehr-index:
        condition: service_healthy
    ports:
      - 8081:8080
    volumes:
      - ./ci/stats-config.json:/srv/config.json:ro
    # configs:
      # - source: stats-config
        # target: /srv/config.json
    networks:
      - ipehr-network
  ipehr-gateway:
    build: .
    image: ipehr-gateway
    pull_policy: never
    volumes:
      - ./ci/gateway-config.json:/srv/config.json:ro
    # configs:
      # - source: gateway-config
        # target: /srv/config.json
    depends_on:
      ipehr-index:
        condition: service_healthy
      ipehr-stat:
        condition: service_started
    ports:
      - 8080:8080
    networks:
      - ipehr-network
         
# configs:
#   stats-config:
#     file: ./ci/stats-config.json
#   gateway-config:
#     file: ./ci/gateway-config.json

networks:
  ipehr-network:
