// Code generated by MockGen. DO NOT EDIT.
// Source: group_access.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	model "hms/gateway/pkg/docs/model"
	reflect "reflect"
)

// MockGroupAccessService is a mock of GroupAccessService interface
type MockGroupAccessService struct {
	ctrl     *gomock.Controller
	recorder *MockGroupAccessServiceMockRecorder
}

// MockGroupAccessServiceMockRecorder is the mock recorder for MockGroupAccessService
type MockGroupAccessServiceMockRecorder struct {
	mock *MockGroupAccessService
}

// NewMockGroupAccessService creates a new mock instance
func NewMockGroupAccessService(ctrl *gomock.Controller) *MockGroupAccessService {
	mock := &MockGroupAccessService{ctrl: ctrl}
	mock.recorder = &MockGroupAccessServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockGroupAccessService) EXPECT() *MockGroupAccessServiceMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockGroupAccessService) Create(ctx context.Context, userID string, c *model.GroupAccessCreateRequest) (*model.GroupAccess, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userID, c)
	ret0, _ := ret[0].(*model.GroupAccess)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockGroupAccessServiceMockRecorder) Create(ctx, userID, c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGroupAccessService)(nil).Create), ctx, userID, c)
}

// Get mocks base method
func (m *MockGroupAccessService) Get(ctx context.Context, userID string, groupAccessUUID *uuid.UUID) (*model.GroupAccess, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userID, groupAccessUUID)
	ret0, _ := ret[0].(*model.GroupAccess)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockGroupAccessServiceMockRecorder) Get(ctx, userID, groupAccessUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockGroupAccessService)(nil).Get), ctx, userID, groupAccessUUID)
}
