definitions:
  model.QueryColumn:
    properties:
      name:
        type: string
      path:
        type: string
    type: object
  model.QueryRequest:
    properties:
      ehr_id:
        type: string
      fetch:
        type: integer
      offset:
        type: integer
      q:
        type: string
      query_parameters:
        additionalProperties: true
        type: object
    type: object
  model.QueryResponse:
    properties:
      columns:
        items:
          $ref: '#/definitions/model.QueryColumn'
        type: array
      meta:
        properties:
          _created:
            type: string
          _executed_aql:
            type: string
          _generator:
            type: string
          _href:
            type: string
          _schema_version:
            type: string
          _type:
            type: string
        type: object
      name:
        type: string
      q:
        type: string
      rows:
        items: {}
        type: array
    type: object
  stat.ResponsePeriod:
    properties:
      data:
        $ref: '#/definitions/stat.Stat'
      type:
        type: string
    type: object
  stat.ResponseTotal:
    properties:
      data:
        $ref: '#/definitions/stat.Stat'
      month:
        $ref: '#/definitions/stat.Stat'
      type:
        type: string
    type: object
  stat.Stat:
    properties:
      documents:
        type: integer
      patients:
        type: integer
      time:
        type: integer
    type: object
info:
  contact: {}
paths:
  /:
    get:
      description: Retrieve the IPEHR statistics total and current month
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/stat.ResponseTotal'
        "500":
          description: Is returned when an unexpected error occurs while processing
            a request
      summary: Get IPEHR statistics total
      tags:
      - Stat
  /{period}:
    get:
      description: Retrieve the IPEHR statistics per month
      parameters:
      - description: 'Month in YYYYYMM format. Example: 202201'
        in: path
        name: period
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/stat.ResponsePeriod'
        "500":
          description: Is returned when an unexpected error occurs while processing
            a request
      summary: Get IPEHR statistics per month
      tags:
      - Stat
  /query/:
    post:
      consumes:
      - application/json
      description: Performs processing of incoming AQL requests.
      parameters:
      - description: Query request
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/model.QueryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Indicates that the request has succeeded and transaction about
            register new user has been created
          schema:
            $ref: '#/definitions/model.QueryResponse'
        "400":
          description: The request could not be understood by the server due to incorrect
            syntax.
        "408":
          description: The request was canceled due to exceeding the waiting limit.
        "500":
          description: Is returned when an unexpected error occurs while processing
            a request
      summary: Query
      tags:
      - QUERY
swagger: "2.0"
