// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "https://bsn.si/blockchain",
            "email": "support@bsn.si"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Retrieve the IPEHR statistics total and current month",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stat"
                ],
                "summary": "Get IPEHR statistics total",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ResponseTotal"
                        }
                    },
                    "500": {
                        "description": "Is returned when an unexpected error occurs while processing a request"
                    }
                }
            }
        },
        "/{period}": {
            "get": {
                "description": "Retrieve the IPEHR statistics per month",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stat"
                ],
                "summary": "Get IPEHR statistics per month",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Month in YYYYYMM format. Example: 202201",
                        "name": "period",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ResponsePeriod"
                        }
                    },
                    "500": {
                        "description": "Is returned when an unexpected error occurs while processing a request"
                    }
                }
            }
        }
    },
    "definitions": {
        "api.ResponsePeriod": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/api.Stat"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "api.ResponseTotal": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/api.Stat"
                },
                "month": {
                    "$ref": "#/definitions/api.Stat"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "api.Stat": {
            "type": "object",
            "properties": {
                "documents": {
                    "type": "integer"
                },
                "patients": {
                    "type": "integer"
                },
                "time": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "stat.ipehr.org",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "IPEHR Stat API",
	Description:      "IPEHR Stat is an open API service for providing public statistics from the IPEHR system.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
