name: docker-build
on:
  label:
    types:
      - created
      - edited
  push:
    branches:
      - main
      - develop
      - "feature/**"
  pull_request:
    types: [opened, reopened]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    name: docker-build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

     
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Docker meta Stat
        id: meta-stat
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-stat
          # generate Docker tags based on the following events/attributes
          tags: |
            type=sha
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{raw}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push Stat
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.stat
          platforms: linux/amd64
          push: ${{ github.ref_name == 'develop' || github.ref_name == 'main' || github.ref_type == 'tag' }}
          tags: ${{ steps.meta-stat.outputs.tags }}
          labels: ${{ steps.meta-stat.outputs.labels }}

      - name: Docker meta
        id: meta-gateway
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=sha
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{raw}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push Gateway
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.gateway
          platforms: linux/amd64
          push: ${{ github.ref_name == 'develop' || github.ref_name == 'main' || github.ref_type == 'tag' }}
          tags: ${{ steps.meta-gateway.outputs.tags }}
          labels: ${{ steps.meta-gateway.outputs.labels }}
