name: Go

on:
  push:
#    branches: [ "develop" ]
#  pull_request:
#    branches: [ "develop" ]

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    # Service containers to run with `runner-job`
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Unit Test
        run: |
          cd ./src
          go test -v ./pkg/...

  integration_tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: read
      actions: read

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Go mod download
        run: cd ./src && go mod download

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Docker Compose
        run: docker compose up -d

      - name: Run Integration Tests
        run: |
          cd ./src/tests/api
          go test ./... -ci_run
      
      - name: Save Gateway Logs
        if: failure()
        run: docker logs ipehr-gateway-ipehr-gateway-1 > ./gateway.logs

      - name: Archive Gateway Logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: gateway-service-logs
          path: ./gateway.logs

      - name: Save Stat Logs
        if: failure()
        run: docker logs ipehr-gateway-ipehr-stat-1 > ./stat.logs

      - name: Archive Stat Logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: gateway-stat-logs
          path: ./stat.logs

      - name: Stop containers
        if: always()
        run: docker compose -f "docker-compose.yml" down
