name: Go

on:
  push:
#    branches: [ "develop" ]
#  pull_request:
#    branches: [ "develop" ]

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    # Service containers to run with `runner-job`
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Unit Test
      run: |
        cd ./src
        go test -v ./pkg/...

  integration_tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to GitHub Package Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

    - name: Docker version
      run: docker version && docker help

    - name: Docker pull
      run: docker pull ghcr.io/bsn-si/ipehr-blockchain-indexes:develop
    # - name: Log in to the Container registry
    #   uses: docker/login-action@v2
    #   with:
    #     registry: ghcr.io
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.GITHUB_TOKEN }}

    # - uses: KengoTODA/actions-setup-docker-compose@v1
      # with:
        # version: '2.14.2' # the full version of `docker-compose` command
      # env:
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    - name: Run Docker Compose
      run: docker compose -f docker-compose.yml -f docker-compose.test.yml up

    - name: Stop containers
      if: always()
      run: docker compose -f "docker-compose.yml" down
