name: Go

on:
  push:
    branches: [ "develop", "hotfix/IPEHR-50" ]
  pull_request:
    branches: [ "develop" ]

defaults:
  run:
    working-directory: src

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
